steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/datadude-portal-dev:$COMMIT_SHA",
        "--build-arg",
        "env=dev",
        "--network",
        "cloudbuild",
        "--build-arg",
        "NODE_OPTIONS=--max-old-space-size=4096",
        "."
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/datadude-portal-dev:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "datadude-portal-dev"
      - "--image"
      - "gcr.io/$PROJECT_ID/datadude-portal-dev:$COMMIT_SHA"
      - "--region"
      - "asia-east1"

images:
  - "gcr.io/$PROJECT_ID/datadude-portal-dev:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
